FactoryBot.define do
  factory :project do
    sequence(:name) { |n| "Test Project #{n}" }
    # slug, api_key, ingest_key are generated by before_validation callbacks
    environment { "production" }
    retention_days { 90 }
    archive_enabled { false }

    trait :archived do
      archived_at { 1.day.ago }
    end

    trait :archive_enabled do
      archive_enabled { true }
    end

    trait :with_platform do
      platform_project_id { SecureRandom.uuid }
    end

    trait :with_short_retention do
      retention_days { 7 }
    end
  end
end
